version: '3.8'

# Define the services (containers) that make up your application
services:
  # PostgreSQL Database Service
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testdb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app_network

  # Application service
  app:
    build: 
      context: .
      dockerfile: Dockerfile
        
    stdin_open: true
    tty: true
    command: bash
    container_name: Agent_MCP_Server
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      - ENVIRONMENT=docker
    ports:
      - "8000:8000"
      
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

# Define the named volumes used by the services
volumes:
  db_data:
    driver: local

# Define the networks used by the services
networks:
  app_network:
    driver: bridge
