version: '3.8'

# Define the services (containers) that make up your application
services:
  # Service for the PostgreSQL database
  db:
    # Use the official PostgreSQL image from Docker Hub
    image: postgres:13
    # Restart the container if it stops for any reason
    restart: always
    # Environment variables for PostgreSQL configuration
    environment:
    
      # Required: PostgreSQL superuser password
      POSTGRES_PASSWORD: postgres
      # Optional: Default database to create on first run
      POSTGRES_DB: customers
      # Optional: Default superuser username
      POSTGRES_USER: postgres
    # Map port 5432 on the host to port 5432 in the container
    # This allows you to connect to the database from your host machine
    ports:
      - "5432:5432"
    # Define a named volume to persist database data
    # This ensures your data is not lost when the container is stopped or removed
    volumes:
      - db_data:/var/lib/postgresql/data

# Define the named volumes used by the services
volumes:
  # Volume for PostgreSQL data persistence
  db_data: